apiVersion: 1

datasources:
  - name: SonarQube
    type: simplejson
    access: proxy
    url: http://sonarqube:9000
    editable: true
    jsonData:
      httpMethod: GET
    uid: sonarqube

  - name: OWASP ZAP
    type: simplejson
    access: proxy
    url: http://owasp-zap:8080
    editable: true
    jsonData:
      httpMethod: GET
    uid: owasp-zap

  - name: Trivy
    type: simplejson
    access: proxy
    url: http://trivy:8080
    editable: true
    jsonData:
      httpMethod: GET
    uid: trivy

  - name: Falco
    type: influxdb
    access: proxy
    url: http://falco:8086
    database: falco
    editable: true
    uid: falco 