global:
  smtp_smarthost: 'mailhog:1025'
  smtp_from: 'alertmanager@tudominio.com'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'

receivers:
  - name: 'web.hook'
    email_configs:
      - to: 'admin@tudominio.com'
        #subject: 'Alert: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
        #body: |
        #  {{ range .Alerts }}
        #  Alert: {{ .Annotations.summary }}
        #  Description: {{ .Annotations.description }}
        #  Labels: {{ range .Labels.SortedPairs }}{{ .Name }}: {{ .Value }}{{ end }}
        #  {{ end }}
    webhook_configs:
      - url: 'http://host.docker.internal:5001/webhook'
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']
