server:
  address: 0.0.0.0
  port: 8084
spring:
  application:
    name: dms
  security:
    oauth2:
      resourceserver:
        jwt:
          #issuer-uri: http://localhost/auth/realms/arquitecturaTI
          #jwk-set-uri: http://keycloak:8080/realms/arquitecturaTI/protocol/openid-connect/certs
          jwk-set-uri: http://keycloak:8080/auth/realms/arquitecturaTI/protocol/openid-connect/certs
          #issuer-uri: ${KEYCLOAK_ISSUER:http://keycloak:8080/auth/realms/arquitecturaTI}
          #issuer-uri: ${KEYCLOAK_ISSUER:http://localhost:8080/auth/realms/arquitecturaTI}
          issuer-uri: ${KEYCLOAK_PUBLIC_URL:http://localhost/auth}/realms/arquitecturaTI
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,mappings,metrics,env
  endpoint:
    mappings:
      enabled: true
  metrics:
    tags:
      application: dms
app:
  alfresco:
    base-url: ${ALFRESCO_BASE_URL:http://alfresco-repository:8080/alfresco}
    #root-path: "/Company Home"
    username: ${ALFRESCO_USER:admin}
    password: ${ALFRESCO_PASSWORD:admin}
logging:
  level:
    root: INFO
    pe.gob.onp.arquitectura.dms: INFO
    pe.gob.onp.arquitectura.dms.api: INFO    # Para ver logs de controllers
    pe.gob.onp.arquitectura.dms.service: DEBUG  # Para ver logs detallados de services
    org.springframework.web: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"